spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:59161:xe
    username: bitcamp
    password: bitcamppw
    driver-class-name: oracle.jdbc.driver.OracleDriver

  messages:
    basename: messages,errors

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.Oracle10gDialect
#        dialect: org.hibernate.dialect.H2Dialect

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800

logging.level.org.apache.coyote.http11:
  debug